### PR TITLE
Fix breakage on latest nightly.

### PR DESCRIPTION
**Pull request by yotamofek**
Broken here: https://github.com/rust-lang/rust/pull/68524

### CODE REVIEW

**Comment by taiki-e** [comment]
Thanks!

bors r+

**Comment by yotamofek** [comment]
@taiki-e I don't think the bors check should be queued for this long,
quick glance at their docs says this could happen if the bot doesn't have the permissions necessary to force-push into the `staging` branch.
Also, thank YOU! Love this library.

**Comment by yotamofek** [comment]
@taiki-e sorry to bother you, but I think it would be great if we could get this merged 🙏

**Comment by taiki-e** [comment]
Oops, missed the notice, sorry. 

I'll try again with bors and if it doesn't work, merge via the merge button.
bors r+

**Comment by taiki-e** [comment]
> Also, thank YOU! Love this library.

Thank you ❤️

**Comment by taiki-e** [comment]
bors seems to be crashing again.
bors r-

**Comment by taiki-e** [comment]
Published in 0.1.3.

**Pull request merged**
